xfs:xfs_attr_list_sf
xfs:xfs_attr_list_sf_all
xfs:xfs_attr_list_leaf
xfs:xfs_attr_list_leaf_end
xfs:xfs_attr_list_full
xfs:xfs_attr_list_add
xfs:xfs_attr_list_wrong_blk
xfs:xfs_attr_list_notfound
xfs:xfs_attr_leaf_list
xfs:xfs_attr_node_list
xfs:xfs_perag_get
xfs:xfs_perag_get_tag
xfs:xfs_perag_put
xfs:xfs_perag_set_reclaim
xfs:xfs_perag_clear_reclaim
xfs:xfs_perag_set_eofblocks
xfs:xfs_perag_clear_eofblocks
xfs:xfs_read_agf
xfs:xfs_alloc_read_agf
xfs:xfs_read_agi
xfs:xfs_ialloc_read_agi
xfs:xfs_attr_list_node_descend
xfs:xfs_iext_insert
xfs:xfs_iext_remove
xfs:xfs_bmap_pre_update
xfs:xfs_bmap_post_update
xfs:xfs_extlist
xfs:xfs_buf_init
xfs:xfs_buf_free
xfs:xfs_buf_hold
xfs:xfs_buf_rele
xfs:xfs_buf_iodone
xfs:xfs_buf_iorequest
xfs:xfs_buf_bawrite
xfs:xfs_buf_lock
xfs:xfs_buf_lock_done
xfs:xfs_buf_trylock
xfs:xfs_buf_unlock
xfs:xfs_buf_iowait
xfs:xfs_buf_iowait_done
xfs:xfs_buf_delwri_queue
xfs:xfs_buf_delwri_queued
xfs:xfs_buf_delwri_split
xfs:xfs_buf_get_uncached
xfs:xfs_bdstrat_shut
xfs:xfs_buf_item_relse
xfs:xfs_buf_item_iodone
xfs:xfs_buf_item_iodone_async
xfs:xfs_buf_error_relse
xfs:xfs_buf_wait_buftarg
xfs:xfs_trans_read_buf_io
xfs:xfs_trans_read_buf_shut
xfs:xfs_btree_corrupt
xfs:xfs_da_btree_corrupt
xfs:xfs_reset_dqcounts
xfs:xfs_inode_item_push
xfs:xfs_buf_find
xfs:xfs_buf_get
xfs:xfs_buf_read
xfs:xfs_buf_ioerror
xfs:xfs_buf_item_size
xfs:xfs_buf_item_size_ordered
xfs:xfs_buf_item_size_stale
xfs:xfs_buf_item_format
xfs:xfs_buf_item_format_ordered
xfs:xfs_buf_item_format_stale
xfs:xfs_buf_item_ordered
xfs:xfs_buf_item_pin
xfs:xfs_buf_item_unpin
xfs:xfs_buf_item_unpin_stale
xfs:xfs_buf_item_unlock
xfs:xfs_buf_item_unlock_stale
xfs:xfs_buf_item_committed
xfs:xfs_buf_item_push
xfs:xfs_trans_get_buf
xfs:xfs_trans_get_buf_recur
xfs:xfs_trans_getsb
xfs:xfs_trans_getsb_recur
xfs:xfs_trans_read_buf
xfs:xfs_trans_read_buf_recur
xfs:xfs_trans_log_buf
xfs:xfs_trans_brelse
xfs:xfs_trans_bjoin
xfs:xfs_trans_bhold
xfs:xfs_trans_bhold_release
xfs:xfs_trans_binval
xfs:xfs_trans_buf_ordered
xfs:xfs_filestream_free
xfs:xfs_filestream_lookup
xfs:xfs_filestream_scan
xfs:xfs_filestream_pick
xfs:xfs_ilock
xfs:xfs_ilock_nowait
xfs:xfs_ilock_demote
xfs:xfs_iunlock
xfs:xfs_iget_skip
xfs:xfs_iget_reclaim
xfs:xfs_iget_reclaim_fail
xfs:xfs_iget_hit
xfs:xfs_iget_miss
xfs:xfs_getattr
xfs:xfs_setattr
xfs:xfs_readlink
xfs:xfs_inactive_symlink
xfs:xfs_alloc_file_space
xfs:xfs_free_file_space
xfs:xfs_zero_file_space
xfs:xfs_collapse_file_space
xfs:xfs_readdir
xfs:xfs_get_acl
xfs:xfs_vm_bmap
xfs:xfs_file_ioctl
xfs:xfs_file_compat_ioctl
xfs:xfs_ioctl_setattr
xfs:xfs_dir_fsync
xfs:xfs_file_fsync
xfs:xfs_destroy_inode
xfs:xfs_evict_inode
xfs:xfs_update_time
xfs:xfs_dquot_dqalloc
xfs:xfs_dquot_dqdetach
xfs:xfs_inode_set_eofblocks_tag
xfs:xfs_inode_clear_eofblocks_tag
xfs:xfs_inode_free_eofblocks_invalid
xfs:xfs_iomap_prealloc_size
xfs:xfs_ihold
xfs:xfs_irele
xfs:xfs_inode_pin
xfs:xfs_inode_unpin
xfs:xfs_inode_unpin_nowait
xfs:xfs_remove
xfs:xfs_link
xfs:xfs_lookup
xfs:xfs_create
xfs:xfs_symlink
xfs:xfs_rename
xfs:xfs_dqadjust
xfs:xfs_dqreclaim_want
xfs:xfs_dqreclaim_dirty
xfs:xfs_dqreclaim_busy
xfs:xfs_dqreclaim_done
xfs:xfs_dqattach_found
xfs:xfs_dqattach_get
xfs:xfs_dqalloc
xfs:xfs_dqtobp_read
xfs:xfs_dqread
xfs:xfs_dqread_fail
xfs:xfs_dqget_hit
xfs:xfs_dqget_miss
xfs:xfs_dqget_freeing
xfs:xfs_dqget_dup
xfs:xfs_dqput
xfs:xfs_dqput_wait
xfs:xfs_dqput_free
xfs:xfs_dqrele
xfs:xfs_dqflush
xfs:xfs_dqflush_force
xfs:xfs_dqflush_done
xfs:xfs_log_done_nonperm
xfs:xfs_log_done_perm
xfs:xfs_log_umount_write
xfs:xfs_log_grant_sleep
xfs:xfs_log_grant_wake
xfs:xfs_log_grant_wake_up
xfs:xfs_log_reserve
xfs:xfs_log_reserve_exit
xfs:xfs_log_regrant
xfs:xfs_log_regrant_exit
xfs:xfs_log_regrant_reserve_enter
xfs:xfs_log_regrant_reserve_exit
xfs:xfs_log_regrant_reserve_sub
xfs:xfs_log_ungrant_enter
xfs:xfs_log_ungrant_exit
xfs:xfs_log_ungrant_sub
xfs:xfs_log_force
xfs:xfs_ail_push
xfs:xfs_ail_pinned
xfs:xfs_ail_locked
xfs:xfs_ail_flushing
xfs:xfs_ail_insert
xfs:xfs_ail_move
xfs:xfs_ail_delete
xfs:xfs_log_assign_tail_lsn
xfs:xfs_file_read
xfs:xfs_file_buffered_write
xfs:xfs_file_direct_write
xfs:xfs_file_splice_read
xfs:xfs_writepage
xfs:xfs_releasepage
xfs:xfs_invalidatepage
xfs:xfs_map_blocks_found
xfs:xfs_map_blocks_alloc
xfs:xfs_get_blocks_found
xfs:xfs_get_blocks_alloc
xfs:xfs_delalloc_enospc
xfs:xfs_unwritten_convert
xfs:xfs_get_blocks_notfound
xfs:xfs_setfilesize
xfs:xfs_itruncate_extents_start
xfs:xfs_itruncate_extents_end
xfs:xfs_pagecache_inval
xfs:xfs_bunmap
xfs:xfs_extent_busy
xfs:xfs_extent_busy_enomem
xfs:xfs_extent_busy_force
xfs:xfs_extent_busy_reuse
xfs:xfs_extent_busy_clear
xfs:xfs_extent_busy_trim
xfs:xfs_trans_commit_lsn
xfs:xfs_agf
xfs:xfs_free_extent
xfs:xfs_alloc_exact_done
xfs:xfs_alloc_exact_notfound
xfs:xfs_alloc_exact_error
xfs:xfs_alloc_near_nominleft
xfs:xfs_alloc_near_first
xfs:xfs_alloc_near_greater
xfs:xfs_alloc_near_lesser
xfs:xfs_alloc_near_error
xfs:xfs_alloc_near_noentry
xfs:xfs_alloc_near_busy
xfs:xfs_alloc_size_neither
xfs:xfs_alloc_size_noentry
xfs:xfs_alloc_size_nominleft
xfs:xfs_alloc_size_done
xfs:xfs_alloc_size_error
xfs:xfs_alloc_size_busy
xfs:xfs_alloc_small_freelist
xfs:xfs_alloc_small_notenough
xfs:xfs_alloc_small_done
xfs:xfs_alloc_small_error
xfs:xfs_alloc_vextent_badargs
xfs:xfs_alloc_vextent_nofix
xfs:xfs_alloc_vextent_noagbp
xfs:xfs_alloc_vextent_loopfailed
xfs:xfs_alloc_vextent_allfailed
xfs:xfs_dir2_sf_addname
xfs:xfs_dir2_sf_create
xfs:xfs_dir2_sf_lookup
xfs:xfs_dir2_sf_replace
xfs:xfs_dir2_sf_removename
xfs:xfs_dir2_sf_toino4
xfs:xfs_dir2_sf_toino8
xfs:xfs_dir2_sf_to_block
xfs:xfs_dir2_block_addname
xfs:xfs_dir2_block_lookup
xfs:xfs_dir2_block_replace
xfs:xfs_dir2_block_removename
xfs:xfs_dir2_block_to_sf
xfs:xfs_dir2_block_to_leaf
xfs:xfs_dir2_leaf_addname
xfs:xfs_dir2_leaf_lookup
xfs:xfs_dir2_leaf_replace
xfs:xfs_dir2_leaf_removename
xfs:xfs_dir2_leaf_to_block
xfs:xfs_dir2_leaf_to_node
xfs:xfs_dir2_node_addname
xfs:xfs_dir2_node_lookup
xfs:xfs_dir2_node_replace
xfs:xfs_dir2_node_removename
xfs:xfs_dir2_node_to_leaf
xfs:xfs_attr_sf_add
xfs:xfs_attr_sf_addname
xfs:xfs_attr_sf_create
xfs:xfs_attr_sf_lookup
xfs:xfs_attr_sf_remove
xfs:xfs_attr_sf_removename
xfs:xfs_attr_sf_to_leaf
xfs:xfs_attr_leaf_add
xfs:xfs_attr_leaf_add_old
xfs:xfs_attr_leaf_add_new
xfs:xfs_attr_leaf_add_work
xfs:xfs_attr_leaf_addname
xfs:xfs_attr_leaf_create
xfs:xfs_attr_leaf_compact
xfs:xfs_attr_leaf_get
xfs:xfs_attr_leaf_lookup
xfs:xfs_attr_leaf_replace
xfs:xfs_attr_leaf_remove
xfs:xfs_attr_leaf_removename
xfs:xfs_attr_leaf_split
xfs:xfs_attr_leaf_split_before
xfs:xfs_attr_leaf_split_after
xfs:xfs_attr_leaf_clearflag
xfs:xfs_attr_leaf_setflag
xfs:xfs_attr_leaf_flipflags
xfs:xfs_attr_leaf_to_sf
xfs:xfs_attr_leaf_to_node
xfs:xfs_attr_leaf_rebalance
xfs:xfs_attr_leaf_unbalance
xfs:xfs_attr_leaf_toosmall
xfs:xfs_attr_node_addname
xfs:xfs_attr_node_get
xfs:xfs_attr_node_lookup
xfs:xfs_attr_node_replace
xfs:xfs_attr_node_removename
xfs:xfs_attr_fillstate
xfs:xfs_attr_refillstate
xfs:xfs_attr_rmtval_get
xfs:xfs_attr_rmtval_set
xfs:xfs_attr_rmtval_remove
xfs:xfs_da_split
xfs:xfs_da_join
xfs:xfs_da_link_before
xfs:xfs_da_link_after
xfs:xfs_da_unlink_back
xfs:xfs_da_unlink_forward
xfs:xfs_da_root_split
xfs:xfs_da_root_join
xfs:xfs_da_node_add
xfs:xfs_da_node_create
xfs:xfs_da_node_split
xfs:xfs_da_node_remove
xfs:xfs_da_node_rebalance
xfs:xfs_da_node_unbalance
xfs:xfs_da_node_toosmall
xfs:xfs_da_swap_lastblock
xfs:xfs_da_grow_inode
xfs:xfs_da_shrink_inode
xfs:xfs_da_fixhashpath
xfs:xfs_da_path_shift
xfs:xfs_dir2_leafn_add
xfs:xfs_dir2_leafn_remove
xfs:xfs_dir2_grow_inode
xfs:xfs_dir2_shrink_inode
xfs:xfs_dir2_leafn_moveents
xfs:xfs_swap_extent_before
xfs:xfs_swap_extent_after
xfs:xfs_log_recover_item_add
xfs:xfs_log_recover_item_add_cont
xfs:xfs_log_recover_item_reorder_head
xfs:xfs_log_recover_item_reorder_tail
xfs:xfs_log_recover_item_recover
xfs:xfs_log_recover_buf_not_cancel
xfs:xfs_log_recover_buf_cancel
xfs:xfs_log_recover_buf_cancel_add
xfs:xfs_log_recover_buf_cancel_ref_inc
xfs:xfs_log_recover_buf_recover
xfs:xfs_log_recover_buf_inode_buf
xfs:xfs_log_recover_buf_reg_buf
xfs:xfs_log_recover_buf_dquot_buf
xfs:xfs_log_recover_inode_recover
xfs:xfs_log_recover_inode_cancel
xfs:xfs_log_recover_inode_skip
xfs:xfs_discard_extent
xfs:xfs_discard_toosmall
xfs:xfs_discard_exclude
xfs:xfs_discard_busy
kvmmmu:kvm_mmu_pagetable_walk
kvmmmu:kvm_mmu_paging_element
kvmmmu:kvm_mmu_set_accessed_bit
kvmmmu:kvm_mmu_set_dirty_bit
kvmmmu:kvm_mmu_walker_error
kvmmmu:kvm_mmu_get_page
kvmmmu:kvm_mmu_sync_page
kvmmmu:kvm_mmu_unsync_page
kvmmmu:kvm_mmu_prepare_zap_page
kvmmmu:mark_mmio_spte
kvmmmu:handle_mmio_page_fault
kvmmmu:fast_page_fault
kvmmmu:kvm_mmu_invalidate_zap_all_pages
kvmmmu:check_mmio_spte
kvm:kvm_entry
kvm:kvm_hypercall
kvm:kvm_hv_hypercall
kvm:kvm_pio
kvm:kvm_cpuid
kvm:kvm_apic
kvm:kvm_exit
kvm:kvm_inj_virq
kvm:kvm_inj_exception
kvm:kvm_page_fault
kvm:kvm_msr
kvm:kvm_cr
kvm:kvm_pic_set_irq
kvm:kvm_apic_ipi
kvm:kvm_apic_accept_irq
kvm:kvm_eoi
kvm:kvm_pv_eoi
kvm:kvm_nested_vmrun
kvm:kvm_nested_intercepts
kvm:kvm_nested_vmexit
kvm:kvm_nested_vmexit_inject
kvm:kvm_nested_intr_vmexit
kvm:kvm_invlpga
kvm:kvm_skinit
kvm:kvm_emulate_insn
kvm:vcpu_match_mmio
kvm:kvm_write_tsc_offset
kvm:kvm_update_master_clock
kvm:kvm_track_tsc
kvm:kvm_userspace_exit
kvm:kvm_set_irq
kvm:kvm_ioapic_set_irq
kvm:kvm_msi_set_irq
kvm:kvm_ack_irq
kvm:kvm_mmio
kvm:kvm_fpu
kvm:kvm_age_page
kvm:kvm_try_async_get_page
kvm:kvm_async_pf_doublefault
kvm:kvm_async_pf_not_present
kvm:kvm_async_pf_ready
kvm:kvm_async_pf_completed
hda_intel:azx_pcm_trigger
hda_intel:azx_get_position
hda:hda_send_cmd
hda:hda_get_response
hda:hda_bus_reset
hda:hda_power_down
hda:hda_power_up
hda:hda_power_count
hda:hda_unsol_event
mac80211:drv_return_void
mac80211:drv_return_int
mac80211:drv_return_bool
mac80211:drv_return_u32
mac80211:drv_return_u64
mac80211:drv_start
mac80211:drv_get_et_strings
mac80211:drv_get_et_sset_count
mac80211:drv_get_et_stats
mac80211:drv_suspend
mac80211:drv_resume
mac80211:drv_set_wakeup
mac80211:drv_stop
mac80211:drv_add_interface
mac80211:drv_change_interface
mac80211:drv_remove_interface
mac80211:drv_config
mac80211:drv_bss_info_changed
mac80211:drv_prepare_multicast
mac80211:drv_configure_filter
mac80211:drv_set_tim
mac80211:drv_set_key
mac80211:drv_update_tkip_key
mac80211:drv_hw_scan
mac80211:drv_cancel_hw_scan
mac80211:drv_sched_scan_start
mac80211:drv_sched_scan_stop
mac80211:drv_sw_scan_start
mac80211:drv_sw_scan_complete
mac80211:drv_get_stats
mac80211:drv_get_tkip_seq
mac80211:drv_set_frag_threshold
mac80211:drv_set_rts_threshold
mac80211:drv_set_coverage_class
mac80211:drv_sta_notify
mac80211:drv_sta_state
mac80211:drv_sta_rc_update
mac80211:drv_sta_add
mac80211:drv_sta_remove
mac80211:drv_sta_pre_rcu_remove
mac80211:drv_conf_tx
mac80211:drv_get_tsf
mac80211:drv_set_tsf
mac80211:drv_reset_tsf
mac80211:drv_tx_last_beacon
mac80211:drv_ampdu_action
mac80211:drv_get_survey
mac80211:drv_flush
mac80211:drv_channel_switch
mac80211:drv_set_antenna
mac80211:drv_get_antenna
mac80211:drv_remain_on_channel
mac80211:drv_cancel_remain_on_channel
mac80211:drv_set_ringparam
mac80211:drv_get_ringparam
mac80211:drv_tx_frames_pending
mac80211:drv_offchannel_tx_cancel_wait
mac80211:drv_set_bitrate_mask
mac80211:drv_set_rekey_data
mac80211:drv_rssi_callback
mac80211:drv_release_buffered_frames
mac80211:drv_allow_buffered_frames
mac80211:drv_get_rssi
mac80211:drv_mgd_prepare_tx
mac80211:drv_mgd_protect_tdls_discover
mac80211:drv_add_chanctx
mac80211:drv_remove_chanctx
mac80211:drv_change_chanctx
mac80211:drv_switch_vif_chanctx
mac80211:drv_assign_vif_chanctx
mac80211:drv_unassign_vif_chanctx
mac80211:drv_start_ap
mac80211:drv_stop_ap
mac80211:drv_restart_complete
mac80211:drv_ipv6_addr_change
mac80211:drv_join_ibss
mac80211:drv_leave_ibss
mac80211:drv_get_expected_throughput
mac80211:api_start_tx_ba_session
mac80211:api_start_tx_ba_cb
mac80211:api_stop_tx_ba_session
mac80211:api_stop_tx_ba_cb
mac80211:api_restart_hw
mac80211:api_beacon_loss
mac80211:api_connection_loss
mac80211:api_cqm_rssi_notify
mac80211:api_scan_completed
mac80211:api_sched_scan_results
mac80211:api_sched_scan_stopped
mac80211:api_sta_block_awake
mac80211:api_chswitch_done
mac80211:api_ready_on_channel
mac80211:api_remain_on_channel_expired
mac80211:api_gtk_rekey_notify
mac80211:api_enable_rssi_reports
mac80211:api_eosp
mac80211:api_sta_set_buffered
mac80211:wake_queue
mac80211:stop_queue
mac80211:drv_set_default_unicast_key
mac80211:api_radar_detected
mac80211:drv_channel_switch_beacon
cfg80211:rdev_suspend
cfg80211:rdev_return_int
cfg80211:rdev_scan
cfg80211:rdev_resume
cfg80211:rdev_return_void
cfg80211:rdev_get_antenna
cfg80211:rdev_rfkill_poll
cfg80211:rdev_set_wakeup
cfg80211:rdev_add_virtual_intf
cfg80211:rdev_return_wdev
cfg80211:rdev_del_virtual_intf
cfg80211:rdev_change_virtual_intf
cfg80211:rdev_add_key
cfg80211:rdev_get_key
cfg80211:rdev_del_key
cfg80211:rdev_set_default_key
cfg80211:rdev_set_default_mgmt_key
cfg80211:rdev_start_ap
cfg80211:rdev_change_beacon
cfg80211:rdev_stop_ap
cfg80211:rdev_sched_scan_stop
cfg80211:rdev_set_rekey_data
cfg80211:rdev_get_mesh_config
cfg80211:rdev_leave_mesh
cfg80211:rdev_leave_ibss
cfg80211:rdev_flush_pmksa
cfg80211:rdev_add_station
cfg80211:rdev_change_station
cfg80211:rdev_del_station
cfg80211:rdev_get_station
cfg80211:rdev_del_mpath
cfg80211:rdev_set_wds_peer
cfg80211:rdev_dump_station
cfg80211:rdev_return_int_station_info
cfg80211:rdev_add_mpath
cfg80211:rdev_change_mpath
cfg80211:rdev_get_mpath
cfg80211:rdev_dump_mpath
cfg80211:rdev_return_int_mpath_info
cfg80211:rdev_return_int_mesh_config
cfg80211:rdev_update_mesh_config
cfg80211:rdev_join_mesh
cfg80211:rdev_change_bss
cfg80211:rdev_set_txq_params
cfg80211:rdev_libertas_set_mesh_channel
cfg80211:rdev_set_monitor_channel
cfg80211:rdev_auth
cfg80211:rdev_assoc
cfg80211:rdev_deauth
cfg80211:rdev_disassoc
cfg80211:rdev_mgmt_tx_cancel_wait
cfg80211:rdev_set_power_mgmt
cfg80211:rdev_connect
cfg80211:rdev_set_cqm_rssi_config
cfg80211:rdev_set_cqm_txe_config
cfg80211:rdev_disconnect
cfg80211:rdev_join_ibss
cfg80211:rdev_set_wiphy_params
cfg80211:rdev_get_tx_power
cfg80211:rdev_set_tx_power
cfg80211:rdev_return_int_int
cfg80211:rdev_set_bitrate_mask
cfg80211:rdev_mgmt_frame_register
cfg80211:rdev_return_int_tx_rx
cfg80211:rdev_return_void_tx_rx
cfg80211:rdev_set_antenna
cfg80211:rdev_sched_scan_start
cfg80211:rdev_tdls_mgmt
cfg80211:rdev_dump_survey
cfg80211:rdev_return_int_survey_info
cfg80211:rdev_tdls_oper
cfg80211:rdev_probe_client
cfg80211:rdev_set_pmksa
cfg80211:rdev_del_pmksa
cfg80211:rdev_remain_on_channel
cfg80211:rdev_return_int_cookie
cfg80211:rdev_cancel_remain_on_channel
cfg80211:rdev_mgmt_tx
cfg80211:rdev_set_noack_map
cfg80211:rdev_get_channel
cfg80211:rdev_return_chandef
cfg80211:rdev_start_p2p_device
cfg80211:rdev_stop_p2p_device
cfg80211:rdev_set_mac_acl
cfg80211:rdev_update_ft_ies
cfg80211:rdev_crit_proto_start
cfg80211:rdev_crit_proto_stop
cfg80211:rdev_channel_switch
cfg80211:rdev_set_qos_map
cfg80211:rdev_set_ap_chanwidth
cfg80211:cfg80211_return_bool
cfg80211:cfg80211_notify_new_peer_candidate
cfg80211:cfg80211_send_rx_auth
cfg80211:cfg80211_send_rx_assoc
cfg80211:cfg80211_rx_unprot_mlme_mgmt
cfg80211:cfg80211_rx_mlme_mgmt
cfg80211:cfg80211_tx_mlme_mgmt
cfg80211:cfg80211_send_auth_timeout
cfg80211:cfg80211_send_assoc_timeout
cfg80211:cfg80211_michael_mic_failure
cfg80211:cfg80211_ready_on_channel
cfg80211:cfg80211_ready_on_channel_expired
cfg80211:cfg80211_new_sta
cfg80211:cfg80211_del_sta
cfg80211:cfg80211_rx_mgmt
cfg80211:cfg80211_mgmt_tx_status
cfg80211:cfg80211_cqm_rssi_notify
cfg80211:cfg80211_reg_can_beacon
cfg80211:cfg80211_chandef_dfs_required
cfg80211:cfg80211_ch_switch_notify
cfg80211:cfg80211_radar_event
cfg80211:cfg80211_cac_event
cfg80211:cfg80211_rx_spurious_frame
cfg80211:cfg80211_rx_unexpected_4addr_frame
cfg80211:cfg80211_ibss_joined
cfg80211:cfg80211_probe_status
cfg80211:cfg80211_cqm_pktloss_notify
cfg80211:cfg80211_gtk_rekey_notify
cfg80211:cfg80211_pmksa_candidate_notify
cfg80211:cfg80211_report_obss_beacon
cfg80211:cfg80211_tdls_oper_request
cfg80211:cfg80211_scan_done
cfg80211:cfg80211_sched_scan_results
cfg80211:cfg80211_sched_scan_stopped
cfg80211:cfg80211_get_bss
cfg80211:cfg80211_inform_bss_width_frame
cfg80211:cfg80211_return_bss
cfg80211:cfg80211_return_uint
cfg80211:cfg80211_return_u32
cfg80211:cfg80211_report_wowlan_wakeup
cfg80211:cfg80211_ft_event
cfg80211:cfg80211_stop_iface
v4l2:v4l2_dqbuf
v4l2:v4l2_qbuf
sunrpc:rpc_call_status
sunrpc:rpc_bind_status
sunrpc:rpc_connect_status
sunrpc:rpc_task_begin
sunrpc:rpc_task_run_action
sunrpc:rpc_task_complete
sunrpc:rpc_task_sleep
sunrpc:rpc_task_wakeup
sunrpc:rpc_socket_state_change
sunrpc:rpc_socket_connect
sunrpc:rpc_socket_error
sunrpc:rpc_socket_reset_connection
sunrpc:rpc_socket_close
sunrpc:rpc_socket_shutdown
i915:i915_pipe_update_start
i915:i915_pipe_update_vblank_evaded
i915:i915_pipe_update_end
i915:i915_gem_object_create
i915:i915_vma_bind
i915:i915_vma_unbind
i915:i915_gem_object_change_domain
i915:i915_gem_object_pwrite
i915:i915_gem_object_pread
i915:i915_gem_object_fault
i915:i915_gem_object_clflush
i915:i915_gem_object_destroy
i915:i915_gem_evict
i915:i915_gem_evict_everything
i915:i915_gem_evict_vm
i915:i915_gem_ring_sync_to
i915:i915_gem_ring_dispatch
i915:i915_gem_ring_flush
i915:i915_gem_request_add
i915:i915_gem_request_complete
i915:i915_gem_request_retire
i915:i915_gem_request_wait_begin
i915:i915_gem_request_wait_end
i915:i915_ring_wait_begin
i915:i915_ring_wait_end
i915:i915_flip_request
i915:i915_flip_complete
i915:i915_reg_rw
i915:intel_gpu_freq_change
drm:drm_vblank_event
drm:drm_vblank_event_queued
drm:drm_vblank_event_delivered
skb:kfree_skb - Tracepoint for free an sk_buff
skb:consume_skb - 
skb:skb_copy_datagram_iovec
net:net_dev_start_xmit
net:net_dev_xmit
net:net_dev_queue
net:netif_receive_skb
net:netif_rx
net:napi_gro_frags_entry
net:napi_gro_receive_entry
net:netif_receive_skb_entry
net:netif_rx_entry
net:netif_rx_ni_entry
napi:napi_poll
sock:sock_rcvqueue_full
sock:sock_exceed_buf_limit
udp:udp_fail_queue_rcv_skb
ras:mc_event
ras:aer_event
iommu:add_device_to_group
iommu:remove_device_from_group
iommu:attach_device_to_domain
iommu:detach_device_from_domain
iommu:map
iommu:unmap
iommu:io_page_fault
i2c:i2c_write
i2c:i2c_read
i2c:i2c_reply
i2c:i2c_result
i2c:smbus_write
i2c:smbus_read
i2c:smbus_reply
i2c:smbus_result
xhci-hcd:xhci_dbg_address
xhci-hcd:xhci_dbg_context_change
xhci-hcd:xhci_dbg_quirks
xhci-hcd:xhci_dbg_reset_ep
xhci-hcd:xhci_dbg_cancel_urb
xhci-hcd:xhci_dbg_init
xhci-hcd:xhci_dbg_ring_expansion
xhci-hcd:xhci_address_ctx
xhci-hcd:xhci_cmd_completion
scsi:scsi_dispatch_cmd_start
scsi:scsi_dispatch_cmd_error
scsi:scsi_dispatch_cmd_done
scsi:scsi_dispatch_cmd_timeout
scsi:scsi_eh_wakeup
fence:fence_annotate_wait_on
fence:fence_emit
fence:fence_init
fence:fence_destroy
fence:fence_enable_signal
fence:fence_signaled
fence:fence_wait_start
fence:fence_wait_end
regmap:regmap_reg_write
regmap:regmap_reg_read
regmap:regmap_reg_read_cache
regmap:regmap_hw_read_start
regmap:regmap_hw_read_done
regmap:regmap_hw_write_start
regmap:regmap_hw_write_done
regmap:regcache_sync
regmap:regmap_cache_only
regmap:regmap_cache_bypass
regmap:regmap_async_write_start
regmap:regmap_async_io_complete
regmap:regmap_async_complete_start
regmap:regmap_async_complete_done
regmap:regcache_drop_region
random:add_device_randomness
random:mix_pool_bytes
random:mix_pool_bytes_nolock
random:credit_entropy_bits
random:push_to_pool
random:debit_entropy
random:add_input_randomness
random:add_disk_randomness
random:xfer_secondary_pool
random:get_random_bytes
random:get_random_bytes_arch
random:extract_entropy
random:extract_entropy_user
random:random_read
random:urandom_read
gpio:gpio_direction
gpio:gpio_value
swiotlb:swiotlb_bounced
block:block_touch_buffer - mark a buffer accessed. Called from touch_buffer().
block:block_dirty_buffer - mark a buffer dirty. Called from mark_buffer_dirty().
block:block_rq_abort - abort block operation request. Called immediately after pending block IO operation request @rq in queue @q is aborted.
block:block_rq_requeue - place block IO request back on a queue. The block operation request @rq is being placed back into queue @q.  For some reason the request was not completed and needs to be put back in the queue.
block:block_rq_complete - block IO operation completed by device driver. The block_rq_complete tracepoint event indicates that some portion of operation request has been completed by the device driver.
block:block_rq_insert - insert block operation request into queue. Called immediately before block operation request @rq is inserted into queue @q.
block:block_rq_issue - issue pending block IO request operation to device driver. Called when block operation request @rq from queue @q is sent to a device driver for processing.
block:block_bio_bounce - used bounce buffer when processing block operation. A bounce buffer was used to handle the block operation @bio in @q. This occurs when hardware limitations prevent a direct transfer of data between the @bio data memory area and the IO device.  Use of a bounce buffer requires extra copying of data and decreases performance.
block:block_bio_complete - completed all work on the block operation.  This tracepoint indicates there is no further work to do on this block IO operation @bio.
block:block_bio_backmerge - merging block operation to the end of an existing operation. Merging block request @bio to the end of an existing block request in queue @q.
block:block_bio_frontmerge - merging block operation to the beginning of an existing operation. Merging block IO operation @bio to the beginning of an existing block operation in queue @q.
block:block_bio_queue - putting new block IO operation in queue. About to place the block IO operation @bio into queue @q.
block:block_getrq - get a free request entry in queue for block IO operations. A request struct for queue @q has been allocated to handle the block IO operation @bio.
block:block_sleeprq - waiting to get a free request entry in queue for block IO operation. In the case where a request struct cannot be provided for queue @q the process needs to wait for an request struct to become available.  This tracepoint event is generated each time the process goes to sleep waiting for request struct become available.
block:block_plug - keep operations requests in request queue. Plug the request queue @q.  Do not allow block operation requests to be sent to the device driver. Instead, accumulate requests in the queue to improve throughput performance of the block device.
block:block_unplug - release of operations requests in request queue. Unplug request queue @q because device driver is scheduled to work on elements in the request queue.
block:block_split - split a single bio struct into two bio structs. The bio request @bio in request queue @q needs to be split into two bio requests. The newly created @bio request starts at @new_sector. This split may be required due to hardware limitation such as operation crossing device boundaries in a RAID system.
block:block_bio_remap - map request for a logical device to the raw device. An operation for a logical device has been mapped to the raw block device.
block:block_rq_remap - map request for a block operation request.  The block operation request @rq in @q has been remapped.  The block operation request @rq holds the current information and @from hold the original sector.
jbd2:jbd2_checkpoint
jbd2:jbd2_start_commit
jbd2:jbd2_commit_locking
jbd2:jbd2_commit_flushing
jbd2:jbd2_commit_logging
jbd2:jbd2_drop_transaction
jbd2:jbd2_end_commit
jbd2:jbd2_submit_inode_data
jbd2:jbd2_handle_start
jbd2:jbd2_handle_extend
jbd2:jbd2_handle_stats
jbd2:jbd2_run_stats
jbd2:jbd2_checkpoint_stats
jbd2:jbd2_update_log_tail
jbd2:jbd2_write_superblock
jbd2:jbd2_lock_buffer_stall
ext4:ext4_free_inode
ext4:ext4_request_inode
ext4:ext4_allocate_inode
ext4:ext4_evict_inode
ext4:ext4_drop_inode
ext4:ext4_mark_inode_dirty
ext4:ext4_begin_ordered_truncate
ext4:ext4_write_begin
ext4:ext4_da_write_begin
ext4:ext4_write_end
ext4:ext4_journalled_write_end
ext4:ext4_da_write_end
ext4:ext4_writepages
ext4:ext4_da_write_pages
ext4:ext4_da_write_pages_extent
ext4:ext4_writepages_result
ext4:ext4_writepage
ext4:ext4_readpage
ext4:ext4_releasepage
ext4:ext4_invalidatepage
ext4:ext4_journalled_invalidatepage
ext4:ext4_discard_blocks
ext4:ext4_mb_new_inode_pa
ext4:ext4_mb_new_group_pa
ext4:ext4_mb_release_inode_pa
ext4:ext4_mb_release_group_pa
ext4:ext4_discard_preallocations
ext4:ext4_mb_discard_preallocations
ext4:ext4_request_blocks
ext4:ext4_allocate_blocks
ext4:ext4_free_blocks
ext4:ext4_sync_file_enter
ext4:ext4_sync_file_exit
ext4:ext4_sync_fs
ext4:ext4_alloc_da_blocks
ext4:ext4_mballoc_alloc
ext4:ext4_mballoc_prealloc
ext4:ext4_mballoc_discard
ext4:ext4_mballoc_free
ext4:ext4_forget
ext4:ext4_da_update_reserve_space
ext4:ext4_da_reserve_space
ext4:ext4_da_release_space
ext4:ext4_mb_bitmap_load
ext4:ext4_mb_buddy_bitmap_load
ext4:ext4_read_block_bitmap_load
ext4:ext4_load_inode_bitmap
ext4:ext4_direct_IO_enter
ext4:ext4_direct_IO_exit
ext4:ext4_fallocate_enter
ext4:ext4_punch_hole
ext4:ext4_zero_range
ext4:ext4_fallocate_exit
ext4:ext4_unlink_enter
ext4:ext4_unlink_exit
ext4:ext4_truncate_enter
ext4:ext4_truncate_exit
ext4:ext4_ext_convert_to_initialized_enter
ext4:ext4_ext_convert_to_initialized_fastpath
ext4:ext4_ext_map_blocks_enter
ext4:ext4_ind_map_blocks_enter
ext4:ext4_ext_map_blocks_exit
ext4:ext4_ind_map_blocks_exit
ext4:ext4_ext_load_extent
ext4:ext4_load_inode
ext4:ext4_journal_start
ext4:ext4_journal_start_reserved
ext4:ext4_trim_extent
ext4:ext4_trim_all_free
ext4:ext4_ext_handle_unwritten_extents
ext4:ext4_get_implied_cluster_alloc_exit
ext4:ext4_ext_put_in_cache
ext4:ext4_ext_in_cache
ext4:ext4_find_delalloc_range
ext4:ext4_get_reserved_cluster_alloc
ext4:ext4_ext_show_extent
ext4:ext4_remove_blocks
ext4:ext4_ext_rm_leaf
ext4:ext4_ext_rm_idx
ext4:ext4_ext_remove_space
ext4:ext4_ext_remove_space_done
ext4:ext4_es_insert_extent
ext4:ext4_es_cache_extent
ext4:ext4_es_remove_extent
ext4:ext4_es_find_delayed_extent_range_enter
ext4:ext4_es_find_delayed_extent_range_exit
ext4:ext4_es_lookup_extent_enter
ext4:ext4_es_lookup_extent_exit
ext4:ext4_es_shrink_enter
ext4:ext4_es_shrink_exit
ext4:ext4_collapse_range
filelock:break_lease_noblock
filelock:break_lease_block
filelock:break_lease_unblock
filelock:generic_add_lease
filelock:generic_delete_lease
filelock:time_out_leases
writeback:writeback_dirty_page
writeback:writeback_dirty_inode_start
writeback:writeback_dirty_inode
writeback:writeback_write_inode_start
writeback:writeback_write_inode
writeback:writeback_queue
writeback:writeback_exec
writeback:writeback_start
writeback:writeback_written
writeback:writeback_wait
writeback:writeback_pages_written
writeback:writeback_nowork
writeback:writeback_wake_background
writeback:writeback_bdi_register
writeback:writeback_bdi_unregister
writeback:wbc_writepage
writeback:writeback_queue_io
writeback:global_dirty_state
writeback:bdi_dirty_ratelimit
writeback:balance_dirty_pages
writeback:writeback_sb_inodes_requeue
writeback:writeback_congestion_wait
writeback:writeback_wait_iff_congested
writeback:writeback_single_inode_start
writeback:writeback_single_inode
migrate:mm_migrate_pages
migrate:mm_numa_migrate_ratelimit
compaction:mm_compaction_isolate_migratepages
compaction:mm_compaction_isolate_freepages
compaction:mm_compaction_migratepages
compaction:mm_compaction_begin
compaction:mm_compaction_end
kmem:kmalloc
kmem:kmem_cache_alloc
kmem:kmalloc_node
kmem:kmem_cache_alloc_node
kmem:kfree
kmem:kmem_cache_free
kmem:mm_page_free
kmem:mm_page_free_batched
kmem:mm_page_alloc
kmem:mm_page_alloc_zone_locked
kmem:mm_page_pcpu_drain
kmem:mm_page_alloc_extfrag
vmscan:mm_vmscan_kswapd_sleep
vmscan:mm_vmscan_kswapd_wake
vmscan:mm_vmscan_wakeup_kswapd
vmscan:mm_vmscan_direct_reclaim_begin
vmscan:mm_vmscan_memcg_reclaim_begin
vmscan:mm_vmscan_memcg_softlimit_reclaim_begin
vmscan:mm_vmscan_direct_reclaim_end
vmscan:mm_vmscan_memcg_reclaim_end
vmscan:mm_vmscan_memcg_softlimit_reclaim_end
vmscan:mm_shrink_slab_start
vmscan:mm_shrink_slab_end
vmscan:mm_vmscan_lru_isolate
vmscan:mm_vmscan_memcg_isolate
vmscan:mm_vmscan_writepage
vmscan:mm_vmscan_lru_shrink_inactive
pagemap:mm_lru_insertion
pagemap:mm_lru_activate
oom:oom_score_adj_update
filemap:mm_filemap_delete_from_page_cache
filemap:mm_filemap_add_to_page_cache
context_tracking:user_enter
context_tracking:user_exit
rpm:rpm_suspend
rpm:rpm_resume
rpm:rpm_idle
rpm:rpm_return_int
power:cpu_idle
power:pstate_sample
power:cpu_frequency
power:device_pm_callback_start
power:device_pm_callback_end
power:suspend_resume
power:wakeup_source_activate
power:wakeup_source_deactivate
power:clock_enable
power:clock_disable
power:clock_set_rate
power:power_domain_target
power:pm_qos_add_request
power:pm_qos_update_request
power:pm_qos_remove_request
power:pm_qos_update_request_timeout
power:pm_qos_update_target
power:pm_qos_update_flags
power:dev_pm_qos_add_request
power:dev_pm_qos_update_request
power:dev_pm_qos_remove_request
ftrace:function
module:module_load
module:module_free
module:module_get
module:module_put
module:module_request
timer:timer_init - called when the timer is initialized
timer:timer_start - called when the timer is started
timer:timer_expire_entry - called immediately before the timer callback. Allows to determine the timer latency.
timer:timer_expire_exit - called immediately after the timer callback returns. When used in combination with the timer_expire_entry tracepoint we can determine the runtime of the timer callback function.
timer:timer_cancel - called when the timer is canceled
timer:hrtimer_init - called when the hrtimer is initialized
timer:hrtimer_start - called when the hrtimer is started
timer:hrtimer_expire_entry - called immediately before the hrtimer callback. Allows to determine the timer latency.
timer:hrtimer_expire_exit - called immediately after the hrtimer callback returns. When used in combination with the hrtimer_expire_entry tracepoint we can determine the runtime of the callback function.
timer:hrtimer_cancel - called when the hrtimer is canceled
timer:itimer_state - called when itimer is started or canceled
timer:itimer_expire - called when itimer expires
timer:tick_stop
rcu:rcu_utilization - Tracepoint for start/end markers used for utilization calculations.
printk:console
sched:sched_kthread_stop - Tracepoint for calling kthread_stop, performed to end a kthread.
sched:sched_kthread_stop_ret - Tracepoint for the return value of the kthread stopping.
sched:sched_wakeup - Tracepoint for waking up a task.
sched:sched_wakeup_new - Tracepoint for waking up a new task.
sched:sched_switch - Tracepoint for task switches, performed by the scheduler.
sched:sched_migrate_task - process moving from a CPU move to another CPU.
sched:sched_process_free - Tracepoint for freeing a task.
sched:sched_process_exit - Tracepoint for a task exiting.
sched:sched_wait_task - tracepoint for waiting on task to unschedule.
sched:sched_process_wait - trackpoint for a waiting task.
sched:sched_process_fork - trackpoint for do_fork.
sched:sched_process_exec - Tracepoint for exec.
sched:sched_stat_wait - Tracepoint for accounting wait time (time the task is runnable but not actually running due to scheduler contention).
sched:sched_stat_sleep - Tracepoint for accounting sleep time (time the task is not runnable, including iowait, see below).
sched:sched_stat_iowait - Tracepoint for accounting iowait time (time the task is not runnable due to waiting on IO to complete).
sched:sched_stat_blocked - Tracepoint for accounting blocked time (time the task is in uninterruptible).
sched:sched_stat_runtime - Tracepoint for accounting runtime (time the task is executing on a CPU).
sched:sched_pi_setprio - Tracepoint for showing priority inheritance modifying a tasks priority.
sched:sched_move_numa - Tracks migration of tasks from one runqueue to another. Can be used to detect if automatic NUMA balancing is bouncing between nodes.
sched:sched_stick_numa
sched:sched_swap_numa
sched:sched_wake_idle_without_ipi - Tracepoint for waking a polling cpu without an IPI.
workqueue:workqueue_queue_work - called when a work gets queued. This event occurs when a work is queued immediately or once a delayed work is actually queued on a workqueue (ie: once the delay has been reached).
workqueue:workqueue_activate_work - called when a work gets activated. This event occurs when a queued work is put on the active queue, which happens immediately after queueing unless @max_active limit is reached.
workqueue:workqueue_execute_start - called immediately before the workqueue callback. Allows to track workqueue execution.
workqueue:workqueue_execute_end - called immediately after the workqueue callback. Allows to track workqueue execution.
signal:signal_generate - called when a signal is generated. Current process sends a 'sig' signal to 'task' process with 'info' siginfo.
signal:signal_deliver - called when a signal is delivered. A 'sig' signal is delivered to current process with 'info' siginfo, and it will be handled by 'ka'. Note that some signals reported by signal_generate tracepoint can be lost, ignored or modified (by debugger) before hitting this tracepoint. This means, this can show which signals are actually delivered, but matching generated signals and delivered signals may not be correct.
irq:irq_handler_entry - called immediately before the irq action handler. The struct irqaction pointed to by @action contains various information about the handler, including the device name, @action->name, and the device id, @action->dev_id. When used in conjunction with the irq_handler_exit tracepoint, we can figure out irq handler latencies.
irq:irq_handler_exit - called immediately after the irq action handler returns. If the @ret value is set to IRQ_HANDLED, then we know that the corresponding @action->handler scuccessully handled this irq. Otherwise, the irq might be a shared irq line, or the irq was not handled successfully. Can be used in conjunction with the irq_handler_entry to understand irq handler latencies.
irq:softirq_entry - called immediately before the softirq handler. When used in combination with the softirq_exit tracepoint we can determine the softirq handler routine.
irq:softirq_exit - called immediately after the softirq handler returns. When used in combination with the softirq_entry tracepoint we can determine the softirq handler routine.
irq:softirq_raise - called immediately when a softirq is raised. When used in combination with the softirq_entry tracepoint we can determine the softirq raise to run latency.
task:task_newtask
task:task_rename
exceptions:page_fault_user
exceptions:page_fault_kernel
tlb:tlb_flush
mce:mce_record
raw_syscalls:sys_enter
raw_syscalls:sys_exit
vsyscall:emulate_vsyscall
syscalls:sys_enter_socket
syscalls:sys_exit_socket
syscalls:sys_enter_socketpair
syscalls:sys_exit_socketpair
syscalls:sys_enter_bind
syscalls:sys_exit_bind
syscalls:sys_enter_listen
syscalls:sys_exit_listen
syscalls:sys_enter_accept4
syscalls:sys_exit_accept4
syscalls:sys_enter_accept
syscalls:sys_exit_accept
syscalls:sys_enter_connect
syscalls:sys_exit_connect
syscalls:sys_enter_getsockname
syscalls:sys_exit_getsockname
syscalls:sys_enter_getpeername
syscalls:sys_exit_getpeername
syscalls:sys_enter_sendto
syscalls:sys_exit_sendto
syscalls:sys_enter_recvfrom
syscalls:sys_exit_recvfrom
syscalls:sys_enter_setsockopt
syscalls:sys_exit_setsockopt
syscalls:sys_enter_getsockopt
syscalls:sys_exit_getsockopt
syscalls:sys_enter_shutdown
syscalls:sys_exit_shutdown
syscalls:sys_enter_sendmsg
syscalls:sys_exit_sendmsg
syscalls:sys_enter_sendmmsg
syscalls:sys_exit_sendmmsg
syscalls:sys_enter_recvmsg
syscalls:sys_exit_recvmsg
syscalls:sys_enter_recvmmsg
syscalls:sys_exit_recvmmsg
syscalls:sys_enter_getrandom
syscalls:sys_exit_getrandom
syscalls:sys_enter_ioprio_set
syscalls:sys_exit_ioprio_set
syscalls:sys_enter_ioprio_get
syscalls:sys_exit_ioprio_get
syscalls:sys_enter_add_key
syscalls:sys_exit_add_key
syscalls:sys_enter_request_key
syscalls:sys_exit_request_key
syscalls:sys_enter_keyctl
syscalls:sys_exit_keyctl
syscalls:sys_enter_mq_open
syscalls:sys_exit_mq_open
syscalls:sys_enter_mq_unlink
syscalls:sys_exit_mq_unlink
syscalls:sys_enter_mq_timedsend
syscalls:sys_exit_mq_timedsend
syscalls:sys_enter_mq_timedreceive
syscalls:sys_exit_mq_timedreceive
syscalls:sys_enter_mq_notify
syscalls:sys_exit_mq_notify
syscalls:sys_enter_mq_getsetattr
syscalls:sys_exit_mq_getsetattr
syscalls:sys_enter_shmget
syscalls:sys_exit_shmget
syscalls:sys_enter_shmctl
syscalls:sys_exit_shmctl
syscalls:sys_enter_shmat
syscalls:sys_exit_shmat
syscalls:sys_enter_shmdt
syscalls:sys_exit_shmdt
syscalls:sys_enter_semget
syscalls:sys_exit_semget
syscalls:sys_enter_semctl
syscalls:sys_exit_semctl
syscalls:sys_enter_semtimedop
syscalls:sys_exit_semtimedop
syscalls:sys_enter_semop
syscalls:sys_exit_semop
syscalls:sys_enter_msgget
syscalls:sys_exit_msgget
syscalls:sys_enter_msgctl
syscalls:sys_exit_msgctl
syscalls:sys_enter_msgsnd
syscalls:sys_exit_msgsnd
syscalls:sys_enter_msgrcv
syscalls:sys_exit_msgrcv
syscalls:sys_enter_lookup_dcookie
syscalls:sys_exit_lookup_dcookie
syscalls:sys_enter_quotactl
syscalls:sys_exit_quotactl
syscalls:sys_enter_name_to_handle_at
syscalls:sys_exit_name_to_handle_at
syscalls:sys_enter_open_by_handle_at
syscalls:sys_exit_open_by_handle_at
syscalls:sys_enter_flock
syscalls:sys_exit_flock
syscalls:sys_enter_io_setup
syscalls:sys_exit_io_setup
syscalls:sys_enter_io_destroy
syscalls:sys_exit_io_destroy
syscalls:sys_enter_io_submit
syscalls:sys_exit_io_submit
syscalls:sys_enter_io_cancel
syscalls:sys_exit_io_cancel
syscalls:sys_enter_io_getevents
syscalls:sys_exit_io_getevents
syscalls:sys_enter_eventfd2
syscalls:sys_exit_eventfd2
syscalls:sys_enter_eventfd
syscalls:sys_exit_eventfd
syscalls:sys_enter_timerfd_create
syscalls:sys_exit_timerfd_create
syscalls:sys_enter_timerfd_settime
syscalls:sys_exit_timerfd_settime
syscalls:sys_enter_timerfd_gettime
syscalls:sys_exit_timerfd_gettime
syscalls:sys_enter_signalfd4
syscalls:sys_exit_signalfd4
syscalls:sys_enter_signalfd
syscalls:sys_exit_signalfd
syscalls:sys_enter_epoll_create1
syscalls:sys_exit_epoll_create1
syscalls:sys_enter_epoll_create
syscalls:sys_exit_epoll_create
syscalls:sys_enter_epoll_ctl
syscalls:sys_exit_epoll_ctl
syscalls:sys_enter_epoll_wait
syscalls:sys_exit_epoll_wait
syscalls:sys_enter_epoll_pwait
syscalls:sys_exit_epoll_pwait
syscalls:sys_enter_fanotify_init
syscalls:sys_exit_fanotify_init
syscalls:sys_enter_fanotify_mark
syscalls:sys_exit_fanotify_mark
syscalls:sys_enter_inotify_init1
syscalls:sys_exit_inotify_init1
syscalls:sys_enter_inotify_init
syscalls:sys_exit_inotify_init
syscalls:sys_enter_inotify_add_watch
syscalls:sys_exit_inotify_add_watch
syscalls:sys_enter_inotify_rm_watch
syscalls:sys_exit_inotify_rm_watch
syscalls:sys_enter_statfs
syscalls:sys_exit_statfs
syscalls:sys_enter_fstatfs
syscalls:sys_exit_fstatfs
syscalls:sys_enter_ustat
syscalls:sys_exit_ustat
syscalls:sys_enter_utime
syscalls:sys_exit_utime
syscalls:sys_enter_utimensat
syscalls:sys_exit_utimensat
syscalls:sys_enter_futimesat
syscalls:sys_exit_futimesat
syscalls:sys_enter_utimes
syscalls:sys_exit_utimes
syscalls:sys_enter_sync
syscalls:sys_exit_sync
syscalls:sys_enter_syncfs
syscalls:sys_exit_syncfs
syscalls:sys_enter_fsync
syscalls:sys_exit_fsync
syscalls:sys_enter_fdatasync
syscalls:sys_exit_fdatasync
syscalls:sys_enter_sync_file_range
syscalls:sys_exit_sync_file_range
syscalls:sys_enter_vmsplice
syscalls:sys_exit_vmsplice
syscalls:sys_enter_splice
syscalls:sys_exit_splice
syscalls:sys_enter_tee
syscalls:sys_exit_tee
syscalls:sys_enter_setxattr
syscalls:sys_exit_setxattr
syscalls:sys_enter_lsetxattr
syscalls:sys_exit_lsetxattr
syscalls:sys_enter_fsetxattr
syscalls:sys_exit_fsetxattr
syscalls:sys_enter_getxattr
syscalls:sys_exit_getxattr
syscalls:sys_enter_lgetxattr
syscalls:sys_exit_lgetxattr
syscalls:sys_enter_fgetxattr
syscalls:sys_exit_fgetxattr
syscalls:sys_enter_listxattr
syscalls:sys_exit_listxattr
syscalls:sys_enter_llistxattr
syscalls:sys_exit_llistxattr
syscalls:sys_enter_flistxattr
syscalls:sys_exit_flistxattr
syscalls:sys_enter_removexattr
syscalls:sys_exit_removexattr
syscalls:sys_enter_lremovexattr
syscalls:sys_exit_lremovexattr
syscalls:sys_enter_fremovexattr
syscalls:sys_exit_fremovexattr
syscalls:sys_enter_umount
syscalls:sys_exit_umount
syscalls:sys_enter_mount
syscalls:sys_exit_mount
syscalls:sys_enter_pivot_root
syscalls:sys_exit_pivot_root
syscalls:sys_enter_sysfs
syscalls:sys_exit_sysfs
syscalls:sys_enter_dup3
syscalls:sys_exit_dup3
syscalls:sys_enter_dup2
syscalls:sys_exit_dup2
syscalls:sys_enter_dup
syscalls:sys_exit_dup
syscalls:sys_enter_getcwd
syscalls:sys_exit_getcwd
syscalls:sys_enter_select
syscalls:sys_exit_select
syscalls:sys_enter_pselect6
syscalls:sys_exit_pselect6
syscalls:sys_enter_poll
syscalls:sys_exit_poll
syscalls:sys_enter_ppoll
syscalls:sys_exit_ppoll
syscalls:sys_enter_getdents
syscalls:sys_exit_getdents
syscalls:sys_enter_getdents64
syscalls:sys_exit_getdents64
syscalls:sys_enter_ioctl
syscalls:sys_exit_ioctl
syscalls:sys_enter_fcntl
syscalls:sys_exit_fcntl
syscalls:sys_enter_mknodat
syscalls:sys_exit_mknodat
syscalls:sys_enter_mknod
syscalls:sys_exit_mknod
syscalls:sys_enter_mkdirat
syscalls:sys_exit_mkdirat
syscalls:sys_enter_mkdir
syscalls:sys_exit_mkdir
syscalls:sys_enter_rmdir
syscalls:sys_exit_rmdir
syscalls:sys_enter_unlinkat
syscalls:sys_exit_unlinkat
syscalls:sys_enter_unlink
syscalls:sys_exit_unlink
syscalls:sys_enter_symlinkat
syscalls:sys_exit_symlinkat
syscalls:sys_enter_symlink
syscalls:sys_exit_symlink
syscalls:sys_enter_linkat
syscalls:sys_exit_linkat
syscalls:sys_enter_link
syscalls:sys_exit_link
syscalls:sys_enter_renameat2
syscalls:sys_exit_renameat2
syscalls:sys_enter_renameat
syscalls:sys_exit_renameat
syscalls:sys_enter_rename
syscalls:sys_exit_rename
syscalls:sys_enter_pipe2
syscalls:sys_exit_pipe2
syscalls:sys_enter_pipe
syscalls:sys_exit_pipe
syscalls:sys_enter_newstat
syscalls:sys_exit_newstat
syscalls:sys_enter_newlstat
syscalls:sys_exit_newlstat
syscalls:sys_enter_newfstatat
syscalls:sys_exit_newfstatat
syscalls:sys_enter_newfstat
syscalls:sys_exit_newfstat
syscalls:sys_enter_readlinkat
syscalls:sys_exit_readlinkat
syscalls:sys_enter_readlink
syscalls:sys_exit_readlink
syscalls:sys_enter_lseek
syscalls:sys_exit_lseek
syscalls:sys_enter_read
syscalls:sys_exit_read
syscalls:sys_enter_write
syscalls:sys_exit_write
syscalls:sys_enter_pread64
syscalls:sys_exit_pread64
syscalls:sys_enter_pwrite64
syscalls:sys_exit_pwrite64
syscalls:sys_enter_readv
syscalls:sys_exit_readv
syscalls:sys_enter_writev
syscalls:sys_exit_writev
syscalls:sys_enter_preadv
syscalls:sys_exit_preadv
syscalls:sys_enter_pwritev
syscalls:sys_exit_pwritev
syscalls:sys_enter_sendfile64
syscalls:sys_exit_sendfile64
syscalls:sys_enter_truncate
syscalls:sys_exit_truncate
syscalls:sys_enter_ftruncate
syscalls:sys_exit_ftruncate
syscalls:sys_enter_fallocate
syscalls:sys_exit_fallocate
syscalls:sys_enter_faccessat
syscalls:sys_exit_faccessat
syscalls:sys_enter_access
syscalls:sys_exit_access
syscalls:sys_enter_chdir
syscalls:sys_exit_chdir
syscalls:sys_enter_fchdir
syscalls:sys_exit_fchdir
syscalls:sys_enter_chroot
syscalls:sys_exit_chroot
syscalls:sys_enter_fchmod
syscalls:sys_exit_fchmod
syscalls:sys_enter_fchmodat
syscalls:sys_exit_fchmodat
syscalls:sys_enter_chmod
syscalls:sys_exit_chmod
syscalls:sys_enter_fchownat
syscalls:sys_exit_fchownat
syscalls:sys_enter_chown
syscalls:sys_exit_chown
syscalls:sys_enter_lchown
syscalls:sys_exit_lchown
syscalls:sys_enter_fchown
syscalls:sys_exit_fchown
syscalls:sys_enter_open
syscalls:sys_exit_open
syscalls:sys_enter_openat
syscalls:sys_exit_openat
syscalls:sys_enter_creat
syscalls:sys_exit_creat
syscalls:sys_enter_close
syscalls:sys_exit_close
syscalls:sys_enter_vhangup
syscalls:sys_exit_vhangup
syscalls:sys_enter_move_pages
syscalls:sys_exit_move_pages
syscalls:sys_enter_mbind
syscalls:sys_exit_mbind
syscalls:sys_enter_set_mempolicy
syscalls:sys_exit_set_mempolicy
syscalls:sys_enter_migrate_pages
syscalls:sys_exit_migrate_pages
syscalls:sys_enter_get_mempolicy
syscalls:sys_exit_get_mempolicy
syscalls:sys_enter_swapoff
syscalls:sys_exit_swapoff
syscalls:sys_enter_swapon
syscalls:sys_exit_swapon
syscalls:sys_enter_process_vm_readv
syscalls:sys_exit_process_vm_readv
syscalls:sys_enter_process_vm_writev
syscalls:sys_exit_process_vm_writev
syscalls:sys_enter_msync
syscalls:sys_exit_msync
syscalls:sys_enter_mremap
syscalls:sys_exit_mremap
syscalls:sys_enter_mprotect
syscalls:sys_exit_mprotect
syscalls:sys_enter_brk
syscalls:sys_exit_brk
syscalls:sys_enter_munmap
syscalls:sys_exit_munmap
syscalls:sys_enter_mlock
syscalls:sys_exit_mlock
syscalls:sys_enter_munlock
syscalls:sys_exit_munlock
syscalls:sys_enter_mlockall
syscalls:sys_exit_mlockall
syscalls:sys_enter_munlockall
syscalls:sys_exit_munlockall
syscalls:sys_enter_mincore
syscalls:sys_exit_mincore
syscalls:sys_enter_madvise
syscalls:sys_exit_madvise
syscalls:sys_enter_remap_file_pages
syscalls:sys_exit_remap_file_pages
syscalls:sys_enter_memfd_create
syscalls:sys_exit_memfd_create
syscalls:sys_enter_readahead
syscalls:sys_exit_readahead
syscalls:sys_enter_fadvise64
syscalls:sys_exit_fadvise64
syscalls:sys_enter_perf_event_open
syscalls:sys_exit_perf_event_open
syscalls:sys_enter_seccomp
syscalls:sys_exit_seccomp
syscalls:sys_enter_kexec_load
syscalls:sys_exit_kexec_load
syscalls:sys_enter_kexec_file_load
syscalls:sys_exit_kexec_file_load
syscalls:sys_enter_acct
syscalls:sys_exit_acct
syscalls:sys_enter_delete_module
syscalls:sys_exit_delete_module
syscalls:sys_enter_init_module
syscalls:sys_exit_init_module
syscalls:sys_enter_finit_module
syscalls:sys_exit_finit_module
syscalls:sys_enter_set_robust_list
syscalls:sys_exit_set_robust_list
syscalls:sys_enter_get_robust_list
syscalls:sys_exit_get_robust_list
syscalls:sys_enter_futex
syscalls:sys_exit_futex
syscalls:sys_enter_timer_create
syscalls:sys_exit_timer_create
syscalls:sys_enter_timer_gettime
syscalls:sys_exit_timer_gettime
syscalls:sys_enter_timer_getoverrun
syscalls:sys_exit_timer_getoverrun
syscalls:sys_enter_timer_settime
syscalls:sys_exit_timer_settime
syscalls:sys_enter_timer_delete
syscalls:sys_exit_timer_delete
syscalls:sys_enter_clock_settime
syscalls:sys_exit_clock_settime
syscalls:sys_enter_clock_gettime
syscalls:sys_exit_clock_gettime
syscalls:sys_enter_clock_adjtime
syscalls:sys_exit_clock_adjtime
syscalls:sys_enter_clock_getres
syscalls:sys_exit_clock_getres
syscalls:sys_enter_clock_nanosleep
syscalls:sys_exit_clock_nanosleep
syscalls:sys_enter_getitimer
syscalls:sys_exit_getitimer
syscalls:sys_enter_setitimer
syscalls:sys_exit_setitimer
syscalls:sys_enter_nanosleep
syscalls:sys_exit_nanosleep
syscalls:sys_enter_alarm
syscalls:sys_exit_alarm
syscalls:sys_enter_time
syscalls:sys_exit_time
syscalls:sys_enter_gettimeofday
syscalls:sys_exit_gettimeofday
syscalls:sys_enter_settimeofday
syscalls:sys_exit_settimeofday
syscalls:sys_enter_adjtimex
syscalls:sys_exit_adjtimex
syscalls:sys_enter_kcmp
syscalls:sys_exit_kcmp
syscalls:sys_enter_syslog
syscalls:sys_exit_syslog
syscalls:sys_enter_sched_setscheduler
syscalls:sys_exit_sched_setscheduler
syscalls:sys_enter_sched_setparam
syscalls:sys_exit_sched_setparam
syscalls:sys_enter_sched_setattr
syscalls:sys_exit_sched_setattr
syscalls:sys_enter_sched_getscheduler
syscalls:sys_exit_sched_getscheduler
syscalls:sys_enter_sched_getparam
syscalls:sys_exit_sched_getparam
syscalls:sys_enter_sched_getattr
syscalls:sys_exit_sched_getattr
syscalls:sys_enter_sched_setaffinity
syscalls:sys_exit_sched_setaffinity
syscalls:sys_enter_sched_getaffinity
syscalls:sys_exit_sched_getaffinity
syscalls:sys_enter_sched_yield
syscalls:sys_exit_sched_yield
syscalls:sys_enter_sched_get_priority_max
syscalls:sys_exit_sched_get_priority_max
syscalls:sys_enter_sched_get_priority_min
syscalls:sys_exit_sched_get_priority_min
syscalls:sys_enter_sched_rr_get_interval
syscalls:sys_exit_sched_rr_get_interval
syscalls:sys_enter_getgroups
syscalls:sys_exit_getgroups
syscalls:sys_enter_setgroups
syscalls:sys_exit_setgroups
syscalls:sys_enter_reboot
syscalls:sys_exit_reboot
syscalls:sys_enter_setns
syscalls:sys_exit_setns
syscalls:sys_enter_setpriority
syscalls:sys_exit_setpriority
syscalls:sys_enter_getpriority
syscalls:sys_exit_getpriority
syscalls:sys_enter_setregid
syscalls:sys_exit_setregid
syscalls:sys_enter_setgid
syscalls:sys_exit_setgid
syscalls:sys_enter_setreuid
syscalls:sys_exit_setreuid
syscalls:sys_enter_setuid
syscalls:sys_exit_setuid
syscalls:sys_enter_setresuid
syscalls:sys_exit_setresuid
syscalls:sys_enter_getresuid
syscalls:sys_exit_getresuid
syscalls:sys_enter_setresgid
syscalls:sys_exit_setresgid
syscalls:sys_enter_getresgid
syscalls:sys_exit_getresgid
syscalls:sys_enter_setfsuid
syscalls:sys_exit_setfsuid
syscalls:sys_enter_setfsgid
syscalls:sys_exit_setfsgid
syscalls:sys_enter_getpid
syscalls:sys_exit_getpid
syscalls:sys_enter_gettid
syscalls:sys_exit_gettid
syscalls:sys_enter_getppid
syscalls:sys_exit_getppid
syscalls:sys_enter_getuid
syscalls:sys_exit_getuid
syscalls:sys_enter_geteuid
syscalls:sys_exit_geteuid
syscalls:sys_enter_getgid
syscalls:sys_exit_getgid
syscalls:sys_enter_getegid
syscalls:sys_exit_getegid
syscalls:sys_enter_times
syscalls:sys_exit_times
syscalls:sys_enter_setpgid
syscalls:sys_exit_setpgid
syscalls:sys_enter_getpgid
syscalls:sys_exit_getpgid
syscalls:sys_enter_getpgrp
syscalls:sys_exit_getpgrp
syscalls:sys_enter_getsid
syscalls:sys_exit_getsid
syscalls:sys_enter_setsid
syscalls:sys_exit_setsid
syscalls:sys_enter_newuname
syscalls:sys_exit_newuname
syscalls:sys_enter_sethostname
syscalls:sys_exit_sethostname
syscalls:sys_enter_setdomainname
syscalls:sys_exit_setdomainname
syscalls:sys_enter_getrlimit
syscalls:sys_exit_getrlimit
syscalls:sys_enter_prlimit64
syscalls:sys_exit_prlimit64
syscalls:sys_enter_setrlimit
syscalls:sys_exit_setrlimit
syscalls:sys_enter_getrusage
syscalls:sys_exit_getrusage
syscalls:sys_enter_umask
syscalls:sys_exit_umask
syscalls:sys_enter_prctl
syscalls:sys_exit_prctl
syscalls:sys_enter_getcpu
syscalls:sys_exit_getcpu
syscalls:sys_enter_sysinfo
syscalls:sys_exit_sysinfo
syscalls:sys_enter_restart_syscall
syscalls:sys_exit_restart_syscall
syscalls:sys_enter_rt_sigprocmask
syscalls:sys_exit_rt_sigprocmask
syscalls:sys_enter_rt_sigpending
syscalls:sys_exit_rt_sigpending
syscalls:sys_enter_rt_sigtimedwait
syscalls:sys_exit_rt_sigtimedwait
syscalls:sys_enter_kill
syscalls:sys_exit_kill
syscalls:sys_enter_tgkill
syscalls:sys_exit_tgkill
syscalls:sys_enter_tkill
syscalls:sys_exit_tkill
syscalls:sys_enter_rt_sigqueueinfo
syscalls:sys_exit_rt_sigqueueinfo
syscalls:sys_enter_rt_tgsigqueueinfo
syscalls:sys_exit_rt_tgsigqueueinfo
syscalls:sys_enter_sigaltstack
syscalls:sys_exit_sigaltstack
syscalls:sys_enter_rt_sigaction
syscalls:sys_exit_rt_sigaction
syscalls:sys_enter_pause
syscalls:sys_exit_pause
syscalls:sys_enter_rt_sigsuspend
syscalls:sys_exit_rt_sigsuspend
syscalls:sys_enter_ptrace
syscalls:sys_exit_ptrace
syscalls:sys_enter_capget
syscalls:sys_exit_capget
syscalls:sys_enter_capset
syscalls:sys_exit_capset
syscalls:sys_enter_sysctl
syscalls:sys_exit_sysctl
syscalls:sys_enter_exit
syscalls:sys_exit_exit
syscalls:sys_enter_exit_group
syscalls:sys_exit_exit_group
syscalls:sys_enter_waitid
syscalls:sys_exit_waitid
syscalls:sys_enter_wait4
syscalls:sys_exit_wait4
syscalls:sys_enter_personality
syscalls:sys_exit_personality
syscalls:sys_enter_set_tid_address
syscalls:sys_exit_set_tid_address
syscalls:sys_enter_unshare
syscalls:sys_exit_unshare
syscalls:sys_enter_mmap
syscalls:sys_exit_mmap
nmi:nmi_handler
irq_vectors:local_timer_entry
irq_vectors:local_timer_exit
irq_vectors:reschedule_entry
irq_vectors:reschedule_exit
irq_vectors:spurious_apic_entry
irq_vectors:spurious_apic_exit
irq_vectors:error_apic_entry
irq_vectors:error_apic_exit
irq_vectors:x86_platform_ipi_entry
irq_vectors:x86_platform_ipi_exit
irq_vectors:irq_work_entry
irq_vectors:irq_work_exit
irq_vectors:call_function_entry
irq_vectors:call_function_exit
irq_vectors:call_function_single_entry
irq_vectors:call_function_single_exit
irq_vectors:threshold_apic_entry
irq_vectors:threshold_apic_exit
irq_vectors:thermal_apic_entry
irq_vectors:thermal_apic_exit
xen:xen_mc_batch
xen:xen_mc_issue
xen:xen_mc_entry
xen:xen_mc_entry_alloc
xen:xen_mc_callback
xen:xen_mc_flush_reason
xen:xen_mc_flush
xen:xen_mc_extend_args
xen:xen_mmu_set_pte
xen:xen_mmu_set_pte_atomic
xen:xen_mmu_set_domain_pte
xen:xen_mmu_set_pte_at
xen:xen_mmu_pte_clear
xen:xen_mmu_set_pmd
xen:xen_mmu_pmd_clear
xen:xen_mmu_set_pud
xen:xen_mmu_set_pgd
xen:xen_mmu_pud_clear
xen:xen_mmu_pgd_clear
xen:xen_mmu_ptep_modify_prot_start
xen:xen_mmu_ptep_modify_prot_commit
xen:xen_mmu_alloc_ptpage
xen:xen_mmu_release_ptpage
xen:xen_mmu_pgd_pin
xen:xen_mmu_pgd_unpin
xen:xen_mmu_flush_tlb_all
xen:xen_mmu_flush_tlb
xen:xen_mmu_flush_tlb_single
xen:xen_mmu_flush_tlb_others
xen:xen_mmu_write_cr3
xen:xen_cpu_write_ldt_entry
xen:xen_cpu_write_idt_entry
xen:xen_cpu_load_idt
xen:xen_cpu_write_gdt_entry
xen:xen_cpu_set_ldt
